### ISSUE TITLE
Error: Route.post() requires a callback function but got a [object Undefined]

### ISSUE THREAD

**Issue by BryanDominic** [gothinkster/node-express-realworld-example-app#100]
I am trying to create a new project from a tutorial on YouTube and I am having the next error: Error: Route.post() requires a callback function but got a [object Undefined] and I dont know how to resolve it. Please help me someone.

Here is the code:
In the folder controllers there are tow files
into home.js
const ctrl = {};

ctrl.index = (req, res) => { 
    res.send('index page'); 
};

module.exports = ctrl;

into image.js
const ctrl = {};

ctrl.index = (req, res) => {

};

ctrl.crate = (req, res) => { 
    
};

ctrl.like = (req, res) => { 
    
};

ctrl.comment = (req, res) => { 
    
};

module.exports = ctrl;

In the folder routes
into index.js
const express = require('express'); 
const router = express.Router();

const home = require('../controllers/home.js'); 
const image = require('../controllers/image.js');

module.exports = app => { 
    
    router.get('/', home.index);
    router.get('/images/:image_id', image.index); 
    router.post('/images', image.create); 
    router.post('/images/:image_id/like', image.like); 
    router.post('/images/image_id/comment', image.comment);

    app.use(router); 

};

in the folder server
into config.js
//settings
const path = require('path');
const exphbs = require('express-handlebars'); 

//midlewares
const morgan = require('morgan');
const multer = require('multer');
const express = require('express');
const erroHandler = require('errorhandler');

//routes
const routes = require('../routes/index'); 

module.exports = app => {

    app.set('port', process.env.PORT || 3000);
    app.set('views', path.join(__dirname, 'views'));
    app.engine('.hbs', exphbs({
        deafultLayout: 'main',
        partialsDir: path.join(app.get('views'), 'partials'),
        layoutsDir: path.join(app.get('views'), 'layouts'),
        extname: '.hbs',
        helpers: require('./helpers')
    }));
    app.set('view engine', '.hbs');

    // middlewares
    app.use(morgan('dev'));
    app.use(multer({dest: path.join(__dirname, '../public/upload/term')}).single('image')) 
    app.use(express.urlencoded({extended: false})); 
    app.use(express.json()) //con json se manejan los likes

    // routes
    routes(app); // al modulo routes se le pasa app

    app.use('/public',express.static(path.join(__dirname, '../public'))) 
    // errorhandles
    if('development' == app.get('env')) {
        app.use(erroHandler)
    }

    return app;
}

and outside of those folders into the folder src there are:
database.js
const mongoose = require('mongoose');

const { database } = require('./keys');

mongoose.connect("mongodb://localhost:27017/namedata", { 
    useNewUrlParser: true 
})
      .then(db => console.log('DB is connected'))
      .catch(err => console.error(err));

index.js
const express = require('express');

const config = require('./server/config');

//database
require('./database');

const app = config(express());

//starting the server
app.listen(app.get('port'), () => {
    console.log('Server on port', app.get('port'));
});

keys.js
module.exports = {

    database: {
        URI: 'mongodb://localhost/namedata'
    }
}

Please help me THANKS!

**Comment by romeo1971** [comment]
did you solve the problem??? Have exactly the same problem!!!
