### ISSUE TITLE
I want to dockerize this sample example

### ISSUE THREAD

**Issue by vmalhotra22** [gothinkster/node-express-realworld-example-app#109]
Hi,

I want to dockerize this sample example. 

Here is my dockerfile code.
------------------------------------------
# Use an official Node runtime as a parent image
FROM node:12.7.0-alpine

# Set the working directory to /app
WORKDIR '/app'

# Copying the rest of the code to the working` directory
COPY . .

RUN npm install
# Install any needed packages specified in package.json
RUN yarn

RUN npm run dev
--------------------------

During Docker build, all the steps works fine except last one which throws MongoDB error. ( attached screenshot)

Not sure if I need to spin a separate mongo DB container along with this.?

Appreciate any sort of help.

Cheers
![IMG_20201004_134344](https://user-images.githubusercontent.com/11765109/95005782-f81c9700-0647-11eb-95d3-76803053c1b5.jpg)

**Comment by gabrielpetry** [comment]
When using containers, you must specify the mongodb container name for the conections, instead of 127.0.0.1 or localhost, check what is the name of the mongo container with something like docker ps, or check the service name in docker-compose.yaml if you are using this,

**Comment by vmalhotra22** [comment]
all sorted..it was 'link' which worked in compose file instead of 'network'.
