### ISSUE TITLE
 Origin is not allowed by Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by pkhadka56** [gothinkster/node-express-realworld-example-app#115]
Hello,

I am facing this issue time and again. Sometimes I don't see the error and sometimes it occurs unexpectedly. I am using react as frontend i.e. **frontend.app.com** whereas for backend I am using node-express i.e. **backend.app.com**. When I browse frontend.app.com I see the following in the browser console. I know the error but how can I solve this? 

```
ERROR Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
    at PromiseRequest../node_modules/superagent/lib/client.js.Request.crossDomainError (client.js:621)
    at XMLHttpRequest.xhr.onreadystatechange (client.js:703)
```

**Comment by Yusadolat** [comment]
This isn't a backend issue. Check your Frontend header.
