### ISSUE TITLE
Getting started should document how to start local MongoDB server

### ISSUE THREAD

**Issue by anishkny** [gothinkster/node-express-realworld-example-app#12]

**Comment by anishkny** [comment]
Addressed by #17

**Comment by pixelbandito** [comment]
I think this should stay open until the PR is merged, right? 

Not having mongoDB mentioned in docs just tripped me up while getting started, and I almost created a duplicate issue because this one was closed.

**Comment by anishkny** [comment]
Fair enough. Leaving open till #17 merged.

**Comment by apai4** [comment]
Merged, thanks @anishkny!
