### ISSUE TITLE
Nodemon dependency in package.js

### ISSUE THREAD

**Issue by aktary** [gothinkster/node-express-realworld-example-app#16]
instructions are `npm install && npm run dev` but `npm run dev` runs `nodemon ./app.s`.  nodemon isn't a dependency or dev dependency in package.json, so it's not installed or defined.

**Comment by deksden** [comment]
Here is PR for fix: https://github.com/gothinkster/node-express-realworld-example-app/pull/18

**Comment by apai4** [comment]
Merged, thanks!
