### ISSUE TITLE
Tags are not saved on server

### ISSUE THREAD

**Issue by deksden** [gothinkster/node-express-realworld-example-app#19]
Tags are slightly broken: can not add any new tag, or update article to add tag.

Tested with React frontend.

Adding tag to database manually will do the trick - tag appears. Try to digg a little bit

**update**: correction - tags are saved for new post, but you should press Enter for tag edit filed to add tag. If you do not press enter, tag in edit field does not added to post. This is separate UI issue, will post in other repo. 

But updating article with new tags did not work.

**Comment by deksden** [comment]
Here is PR to fix: https://github.com/gothinkster/node-express-realworld-example-app/pull/20

**Comment by apai4** [comment]
Fixed by #20, thanks!
