### ISSUE TITLE
PUT / DELETE ARTICLE

### ISSUE THREAD

**Issue by bbobhel166** [gothinkster/node-express-realworld-example-app#2]
Hello,

I am following your angular training. Thanks a lot for your great work !

the app is working perfectly while using your API. I decided to include the node-express-realworld backend. Everything is working well except PUT and DELETE articles methods. I get a 403 Forbidden response. I can delete comments and favorites.

I am new to node and express. I send hours trying to figure out that, without success.

Thanks
Boris

**Comment by nwilson1225** [comment]
I'm having the same issue and haven't found a solution yet.

Thanks,

Nick

**Comment by nwilson1225** [comment]
Well I spoke too soon.  Ended up figuring it out.  Changed put to this to fix it.  Similar fix should work for delete:

```
router.put('/:article', auth.required, function(req, res, next) {
  Promise.all([
    req.payload ? User.findById(req.payload.id) : null,
    req.article.populate('author').execPopulate()
  ]).then(function(results){
    var user = results[0];

    if(req.article.author._id.toString() === req.payload.id.toString()){
      if(typeof req.body.article.title !== 'undefined'){
        console.log("copying title");
        req.article.title = req.body.article.title;
      }

      if(typeof req.body.article.description !== 'undefined'){
        console.log("copying desc");
        req.article.description = req.body.article.description;
      }

      if(typeof req.body.article.body !== 'undefined'){
        console.log("copying body");
        req.article.body = req.body.article.body;
      }

      req.article.save().then(function(article){
        return res.json({article: article.toJSONFor(user)});
      }).catch(next);
    } else {
      return res.sendStatus(403);
    }
  });
});
```

**Comment by juliendubrail** [comment]
Hello, how did you manage to include the node backend. I only get error 404 when running the app.js
