### ISSUE TITLE
bug in user model

### ISSUE THREAD

**Issue by sahand12** [gothinkster/node-express-realworld-example-app#23]
follow method on user mongoose model is implemented incorrectly (models/User.js) line: 78

```javascript
UserSchema.methods.follow = function(id){
  if(this.favorites.indexOf(id) === -1){ // this is wrong it should be this.following.indexOf(id)
    this.following.push(id);
  }

  return this.save();
};
```
the first line of the function is wrong, it should be:
```javascript
if (this.following.indexOf(id) === -1)
```

**Comment by SandeeshS** [comment]
Seems like it was missed when copy pasting the favorites method to create follow method. You can create a PR to get this fixed. I'll create one if you can't.

**Comment by sahand12** [comment]
I'll create a PR.

**Comment by SandeeshS** [comment]
I created the PR since it wasn't a big change and the node version is used commonly for demos. Hope u don't mind.
