### ISSUE TITLE
Need to cast limit & offset to number type

### ISSUE THREAD

**Issue by EricSimons** [gothinkster/node-express-realworld-example-app#3]
Latest version of MongoDB only accepts number type for limit which is throwing errors. Just need to wrap the var definitions with `Number()`

**Comment by EricSimons** [comment]
Fixed with [this PR](https://github.com/gothinkster/node-express-realworld-example-app/pull/7) (thanks @kentcdodds!)

**Comment by kentcdodds** [comment]
Looks like @Federkun beat me to it! I didn't notice that PR, sorry about that.
