### ISSUE TITLE
Not able to configure this node backend.

### ISSUE THREAD

**Issue by rajukiran** [gothinkster/node-express-realworld-example-app#47]
Hello,

I tried to configure this backend, but when i run frontend for each backend call 

> Request URL:http://localhost:3000/users
> Request Method:POST
> Status Code:404 Not Found
> Remote Address:[::1]:3000
> Referrer Policy:no-referrer-when-downgrade

this is i saw at chrome console.

Response:

> {"errors":{"message":"Not Found","error":{"status":404}}}

Can anyone help me how to I fix this?

Thanks,

**Comment by Obs-Dev** [comment]
@rajukiran I believe you are missing `/api`. Should be `http://localhost:3000/api/users`

**Comment by rajukiran** [comment]
Thanks to that,
Yup.. exactly added that last night working fine. Sorry for the update.
