### ISSUE TITLE
I am getting Cannot read property 'username' of undefined

### ISSUE THREAD

**Issue by guruganeshm** [gothinkster/node-express-realworld-example-app#5]
Hi 

This codebase looks really good thanks for providing it, I am a beginner to express environment. **/api/users** is this error something related to Router, bodyParser ? or something else ? help on this would be appreciated. 

In console it morgan an error 500

![screen shot 2017-01-27 at 7 15 36 pm](https://cloud.githubusercontent.com/assets/6544493/22372869/21b854e4-e4c5-11e6-9002-89c8d14e0155.png)

**Comment by tobibe** [comment]
Hello,

I'm getting the same error, did you solve the issue or is there someone who can help me with this.
I extracted the zipfile to a folder, typed "npm install" and run it via npm run or nodemon

If I log this with console.log(req.body), it's empty

Greetings 
tobibe
