### ISSUE TITLE
Where is passport.initialize()?

### ISSUE THREAD

**Issue by jjjjcccjjf** [gothinkster/node-express-realworld-example-app#50]
Sorry, I'm quite new to Node.js. I don't see passport.initialize() anywhere. How are the middlewares supposed to work?

**Comment by ahmadnassri** [comment]
https://github.com/jaredhanson/passport/blob/882d65e69d5b56c6b88dd0248891af9e0d80244b/lib/middleware/initialize.js#L42-L55

**Comment by weirdyang** [comment]
I don't understand why we don't need to call passport.initialize. is it because we're not using sessions?
