### ISSUE TITLE
Error: Not Found at app.js:49:13

### ISSUE THREAD

**Issue by turbothinh** [gothinkster/node-express-realworld-example-app#51]
I cloned and followed the instruction but encountered the error. The same goes for glitch.com instance. Do I have to have any database in the MongoDb installation?

**Comment by eltel** [comment]
Same here :(

**Comment by vincentcheng62** [comment]
Same here

**Comment by Obs-Dev** [comment]
Appears to be catching 404 error. What route are you attempting to access? Are you able to access `http://localhost:3000/api/articles`?

**Comment by meriem-hm** [comment]
same problem here ! what should i do

**Comment by TeodorKolev** [comment]
Same here ..........

**Comment by Obs-Dev** [comment]
@meriem-hm and @TeodorKolev what route (URL in browser) are you attempting to access?

**Comment by meriem-hm** [comment]
@Obs-Dev  the URL that i attempted is http://localhost:3000

**Comment by Obs-Dev** [comment]
@meriem-hm I believe the issue you are experiencing is due to a lack of a valid route being provided. Please try a valid route, such as `http://localhost:3000/api/articles`.

**Comment by loretoparisi** [comment]
I get the same problem after a fresh install of mongodb, and this example.

**Comment by loretoparisi** [comment]
@Obs-Dev in that case I get the api response

```json
{
articles: [ ],
articlesCount: 0
}
```

**Comment by Obs-Dev** [comment]
@loretoparisi this repo only includes an example of working Node.js (Express) API. No interface is provided. You need to either (A) use a tool such as [Postman](https://thinkster.io/tutorials/testing-backend-apis-with-postman) to work with and test your API or (B) configure and connect your own user interface (i.e. [Angular](https://github.com/gothinkster/angular-realworld-example-app)). Let me know if that doesn't answer your question.

**Comment by GitNey** [comment]
How do you connect the vue-js frontend example to the node-express backend example?
