### ISSUE TITLE
Ideas for unit testing?

### ISSUE THREAD

**Issue by kentcdodds** [gothinkster/node-express-realworld-example-app#8]
This may be a little out-of-band for the kind of issues you're looking for, but I was just wondering whether you have any tips on what I could unit test in this repo (for [my workshop](https://github.com/kentcdodds/testing-workshop/issues/1)). Looking through things, there's not a whole lot of logic. It's mostly configuring things. I'm unsure whether there would be any value in unit tests (though Integration and E2E tests would definitely be valuable here). Do you think there's any useful business logic in here that we could test?

Also I'm planning on demonstrating TDD, so if you have any ideas of a feature I could add or a bug I could create and then fix with TDD, that'd be helpful! Thanks!

**Comment by kylealwyn** [comment]
@kentcdodds Unit testing the routes with a mock server is useful to verify that you're receiving the correct responses from your endpoints, given specific payloads. I have a node-express boilerplate repo with mocha/chai unit testing setup: https://github.com/kylealwyn/node-rest-api-boilerplate

The repo also showcases some unit testing for models, although most of the model coverage happens indirectly when testing the routes. 

@gothinkster, sorry for the plug of my repo, great work here!

**Comment by kentcdodds** [comment]
Thanks for your thoughts. Technically, testing the routes is not unit testing, but integration testing. That distinction doesn't normally matter a whole lot, except when you're trying to teach about the distinction 😉

**Comment by kylealwyn** [comment]
Hah, touche. Good luck with the workshop!

**Comment by kentcdodds** [comment]
Perhaps I could pull the function out of [auth](https://github.com/gothinkster/node-express-realworld-example-app/blob/master/routes/auth.js) and test it individually. There's a tiny bit of logic there I guess.... :think:
