### ISSUE TITLE
preload data?

### ISSUE THREAD

**Issue by kentcdodds** [gothinkster/node-express-realworld-example-app#9]
Hey folks! Any ideas on how to load the database with mock data?

**Comment by apai4** [comment]
You could use a library like [mongoose-fixture-loader](https://www.npmjs.com/package/mongoose-fixture-loader) for use with tests (there may be a better library out there depending on your needs) or Mongoose's built in [Model.insertMany](http://mongoosejs.com/docs/api.html#model_Model.insertMany) for seeding a collection into the database

**Comment by kentcdodds** [comment]
Awesome, thanks for those references!
